name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "not a bug", "high priority", "low priority", "backlog", "in progress", "completed"]
assignees:
  - McGRiMTV
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - 1.0.0 (Release)
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, do you agree that it was submitted truthfully to the best of your ability?
      options:
        - label: I agree.
          required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, drag and drop or paste screenshots here to help explain your problem.
    validations:
      required: false